import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  CreateDateColumn,
  ManyToOne,
  JoinColumn,
  Index,
} from 'typeorm';
import { Candidacy } from '../../candidacy/entities/candidacy.entity';

@Entity({ name: 'reminder' })
@Index(['dueDate', 'status'])
export class Reminder {
  @PrimaryGeneratedColumn('increment', { name: 'id_reminder' })
  id: number;

  @Column({ name: 'id_candidacy' })
  candidacyId: number;

  @ManyToOne(() => Candidacy, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'id_candidacy' })
  candidacy: Candidacy;

  @Column({ name: 'due_date', type: 'timestamptz' })
  dueDate: Date;

  @Column({ name: 'reminder_type', length: 50 })
  reminderType: string;

  @Column({ length: 50 })
  status: string;

  @Column({ type: 'text', nullable: true })
  comment?: string;

  @Column({ name: 'auto_generated', default: true })
  autoGenerated: boolean;

  @CreateDateColumn({
    name: 'created_at',
    type: 'timestamptz',
    default: () => 'NOW()',
  })
  createdAt: Date;
}
