import {
  IsNumber,
  IsString,
  MaxLength,
  IsOptional,
  IsBoolean,
  IsDateString,
} from 'class-validator';

export class CreateReminderDto {
  @IsNumber()
  candidacyId: number;

  @IsDateString()
  dueDate: string;

  @IsString()
  @MaxLength(50)
  reminderType: string;

  @IsString()
  @MaxLength(50)
  status: string;

  @IsOptional()
  @IsString()
  comment?: string;

  @IsOptional()
  @IsBoolean()
  autoGenerated?: boolean = true;
}
